export const SecurityRateLimits = {
    ADMIN_MUTATIONS_PER_MIN: 20,
    PASSWORD_CHANGE_ATTEMPTS_PER_MIN: 5,
    PASSWORD_RESET_STATUS_REQUESTS_PER_MIN: 30,
    REPORT_SUBMISSIONS_PER_MIN: 10,
} as const;